// <auto-generated />
using AutoSzereloMuhely.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoSzereloMuhely.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250507195058_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("AutoSzereloMuhely.Domain.Munka", b =>
                {
                    b.Property<int>("MunkaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Allapot")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GyartasEve")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kategoria")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Leiras")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rendszam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Sulyossag")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UgyfelId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MunkaID");

                    b.HasIndex("UgyfelId");

                    b.ToTable("Munkak");
                });

            modelBuilder.Entity("AutoSzereloMuhely.Domain.Ugyfel", b =>
                {
                    b.Property<int>("UgyfelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lakcim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UgyfelNev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UgyfelId");

                    b.ToTable("Ugyfelek");
                });

            modelBuilder.Entity("AutoSzereloMuhely.Domain.Munka", b =>
                {
                    b.HasOne("AutoSzereloMuhely.Domain.Ugyfel", "Ugyfel")
                        .WithMany()
                        .HasForeignKey("UgyfelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ugyfel");
                });
#pragma warning restore 612, 618
        }
    }
}
